# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-components
  version: "0.141.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_components-${{ version }}.tar.gz
  sha256: 1d1bfc5cd4d2a7054e318de0f951c3f2dca2daba86cc3b61818f2421c9963464

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - djc-core-html-parser >=1.0.2
    - typing_extensions >=4.12.2
    - python-tzdata

tests:
  - python:
      imports:
        - django_components
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A way to create simple reusable template components in Django.
  homepage: https://django-components.github.io/django-components/latest/overview/welcome/
  description: |
    Create simple reusable template components in Django.
  repository: https://github.com/django-components/django-components
  documentation: https://django-components.github.io/django-components/latest/reference/api/
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - rxm7706
